package com.example.deleguesapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String name;
    private String forname;
    private String phone;
    private String email;
    private Float moyG;
    private String appreciation;
    private String remarques;
    private Integer etat;
    public static int CREATED_MANUALLY = 1 ;
    public static int CREATED_FROM_REPERTORY = 2 ;
    public static int MOYG_SETTED = 4 ;
    public static int APPRECIATION_SETTED = 8 ;
    public static int REMARQUES_SETTED = 16 ;
    public static int SMS_SENDED = 32 ;
    public static int SMS_RECEIVED = 64 ;
    public static int REEDITED = 128 ;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    /**
     * 
     * @param id
     * @param name
     * @param forname
     * @param phone
     * @param email
     * @param moyG
     * @param appreciation
     * @param remarques
     * @param etat
     * 
     */
    public User(Long id, String name, String forname, String phone, String email, Float moyG, String appreciation, String remarques, Integer etat) {
        this.id = id;
        this.name = name;
        this.forname = forname;
        this.phone = phone;
        this.email = email;
        this.moyG = moyG;
        this.appreciation = appreciation;
        this.remarques = remarques;
        /**
         * @param
         * 1 --> User crée manuellement
         * 2 --> User crée par export repertoire
         * 4 --> Moyenne éditée
         * 8 --> Appreciation éditée
         * 16 --> Remarques editées
         * 32 --> Envoyée par sms par le délégué
         * 64 --> SMS recu par l'eleve
         * 128 --> Réeditée par le delegué
         */
        this.etat = etat;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getForname() {
        return forname;
    }

    public void setForname(String forname) {
        this.forname = forname;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Float getMoyG() {
        return moyG;
    }

    public void setMoyG(Float moyG) {
        this.moyG = moyG;
    }

    public String getAppreciation() {
        return appreciation;
    }

    public void setAppreciation(String appreciation) {
        this.appreciation = appreciation;
    }

    public String getRemarques() {
        return remarques;
    }

    public void setRemarques(String remarques) {
        this.remarques = remarques;
    }

    public Integer getEtat() {
        return etat;
    }

    public void setEtat(Integer etat) {
        this.etat = etat;
    }
    
    public Boolean isCreatedManually(){
    	if ((this.etat & this.CREATED_MANUALLY) == CREATED_MANUALLY)
    			return true;
    	else
    		return false;
    }

}
